### ISSUE TITLE
The type or namespace name 'ApiController' could not be found in Asp Core 2.1 MVC

### ISSUE THREAD

**Issue by Aboodaw** [GuitarRich/sitecore.react.project#5]

**Comment by GuitarRich** [comment]
Can you please add details of what the issue is? When are you getting the error?

**Comment by Aboodaw** [comment]
After create a Web API with ASP.NET Core and Visual Studio Code.....
go to Add empty API Controller >> write [ApiController] before the class controller header

**Comment by GuitarRich** [comment]
This code does not support ASP.NET Core. For Sitecore modules it needs to be ASP.NET 4.x.

**Comment by Aboodaw** [comment]
The issue is solved when VS is updated to 15.7.5
